name: Ops Dispatch
on:
  repository_dispatch:
    types: [ops-run]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  route:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Echo payload
        run: |
          echo "Task: ${{ github.event.client_payload.task }}"
          echo "Args: ${{ toJson(github.event.client_payload.args) }}"

      - name: Bootstrap
        if: github.event.client_payload.task == 'preflight' || github.event.client_payload.task == 'ci'
        run: bash setup/bootstrap.sh

      - name: Preflight
        if: github.event.client_payload.task == 'preflight'
        run: bash qa/preflight.sh

      - name: CI (tests)
        if: github.event.client_payload.task == 'ci'
        run: bash qa/preflight.sh

      - name: Apply patch (branch + commit)
        if: github.event.client_payload.task == 'apply_patch'
        env:
          BRANCH: ${{ github.event.client_payload.args.branch }}
          COMMIT_MSG: ${{ github.event.client_payload.args.commit_msg }}
          PATCH_B64: ${{ github.event.client_payload.args.patch_b64 }}
        run: |
          git checkout -b "$BRANCH"
          echo "$PATCH_B64" | base64 -d | git apply -p0 --whitespace=fix
          git add -A
          git -c user.name="ops-bot" -c user.email="ops-bot@users.noreply.github.com" commit -m "$COMMIT_MSG"
          git push --set-upstream origin "$BRANCH"

      - name: Open PR
        if: github.event.client_payload.task == 'open_pr'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.event.client_payload.args.branch }}
          title: ${{ github.event.client_payload.args.title }}
          body:  ${{ github.event.client_payload.args.body }}
          base:  ${{ github.event.client_payload.args.base || 'main' }}

      - name: Merge PR
        if: github.event.client_payload.task == 'merge_pr'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.client_payload.args.number
            await github.pulls.merge({ owner: context.repo.owner, repo: context.repo.repo, pull_number: pr, merge_method: 'squash' })

      - name: E2E (placeholder)
        if: github.event.client_payload.task == 'e2e'
        run: echo "Add your E2E runner here (Playwright/Cypress)"
