name: Preflight

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Bootstrap repo
        run: bash setup/bootstrap.sh
      - name: Run preflight
        run: bash qa/preflight.sh
